# Generated by Django 4.2 on 2023-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('composition', models.TextField(default='')),
                ('category', models.CharField(choices=[('TU', 'Tuinisia'), ('TUR', 'Turkiye'), ('DO', 'Dubai'), ('QA', 'Qatar'), ('FR', 'France'), ('GR', 'Germany')], max_length=10)),
                ('prodapp', models.TextField(default='')),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
