# Generated by Django 4.2 on 2023-05-12 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TU', 'Tunisia'), ('TUR', 'Turkiye'), ('DO', 'Dubai'), ('QA', 'Qatar'), ('FR', 'France'), ('GR', 'Germany'), ('IT', 'Italy')], max_length=10),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Ariana', 'Ariana'), ('Béja', 'Béja'), ('Bizerte', 'Bizerte'), ('Ben Arous', 'Ben Arous'), ('Gabès', 'Gabès'), ('Jendouba', 'Jendouba'), ('Jendouba', 'Jendouba'), ('\tKasserine', '\tKasserine'), ('Kebili', 'Kebili'), ('\tMahdia', '\tMahdia'), ('Medenine', 'Medenine'), ('Monastir', 'Monastir'), ('\tNabeul', '\tNabeul'), ('Sfax', 'Sfax'), ('\tSiliana', '\tSiliana'), ('\t\tSousse', '\tSousse'), ('Tataouine', 'Tataouine'), ('\tTozeur', '\tTozeur'), ('Tunis', 'Tunis'), ('Zaghouan', 'Zaghouan')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
