# Generated by Django 4.2 on 2023-05-14 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Ariana', 'Ariana'), ('Béja', 'Béja'), ('Bizerte', 'Bizerte'), ('Ben Arous', 'Ben Arous'), ('Gabès', 'Gabès'), ('Jendouba', 'Jendouba'), ('Jendouba', 'Jendouba'), ('\tKasserine', '\tKasserine'), ('Kebili', 'Kebili'), ('\tMahdia', '\tMahdia'), ('Medenine', 'Medenine'), ('Monastir', 'Monastir'), ('\tNabeul', '\tNabeul'), ('Sfax', 'Sfax'), ('\tSiliana', '\tSiliana'), ('\t\tSousse', '\tSousse'), ('Tataouine', 'Tataouine'), ('\tTozeur', '\tTozeur'), ('Tunis', 'Tunis'), ('Zaghouan', 'Zaghouan')], default='pending', max_length=50)),
                ('ordered_data', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
